# data
data_dir: /home/sharv/Projects/joint-clouds/datasets/joint-clouds/data/MNIST2D/

# model
h_dim: 2
e_dim: 16
ze_dim: 16
z_dim: 2
n_latents: 2
hid_dim: 512
activation: silu

# training
gpu: True
n_gpus: 1
n_points_per_cloud: 256
bsz: 16
optimizer: adam
lr: 1e-5
n_epochs: 1000
n_warmup_epochs: 1000

# evaluation
save_dir: /home/sharv/Projects/joint-clouds/datasets/joint-clouds/results/sv
eval_frequency: 10
n_samples: 3
n_points_per_cloud_gen: 512
