# data
data_dir: /pio/scratch/1/mstyp/joint-clouds/data

# model
h1_dim: 2
h2_dim: 2
e_dim: 64
ze_dim: 64
z1_dim: 2
z2_dim: 2
r1_dim: 2
hid_dim: 256
n_layers: 3
activation: silu

# training
gpu: True
n_gpus: 1
n_points_per_cloud: 256
bsz: 1024
lr: 1e-4
n_epochs: 10000
n_warmup_epochs: 0

# evaluation
save_dir: /pio/scratch/1/mstyp/joint-clouds/results/7
eval_frequency: 500
n_samples: 3
n_points_per_cloud_gen: 1024