# data
data_dir: /pio/scratch/1/mstyp/joint-clouds/data

# model
h_dim: 2
e_dim: 16
ze_dim: 16
z_dim: 2
n_latents: 3
hid_dim: 512
activation: silu

# training
gpu: True
n_gpus: 2
n_points_per_cloud: 256
bsz: 1100
optimizer: adam
lr: 1e-5
n_epochs: 50001
n_warmup_epochs: 30

# evaluation
save_dir: /pio/scratch/1/mstyp/joint-clouds/results/0
eval_frequency: 500
n_samples: 3
n_points_per_cloud_gen: 1024