# data
dataset: shapenet # mnist2d, shapenet
data_dir: /pio/gluster/data/shapenet/ShapeNetCore.v2.PC15k # /pio/scratch/1/mstyp/joint-clouds/data
classes: ['chair'] # for shapenet

# model
h_dim: 64
z_dim: 2
emb_dim: 32
encoder_hid_dim: 512
encoder_n_layers: 2
decoder_hid_dim: 2048
decoder_n_layers: 5
use_hypernet: False
hyper_hid_dim: 512
hyper_n_layers: 3

# training
gpu: True
n_gpus: 2
n_points_per_cloud: 512
bsz: 2000
optimizer: adam
lr: 1e-5
n_epochs: 50001
n_warmup_epochs: 30

# evaluation
# save_dir: /pio/scratch/1/mstyp/joint-clouds/results/6
eval_frequency: 500
n_samples: 3
n_points_per_cloud_gen: 1024