# data
data_dir: /pio/scratch/1/mstyp/joint-clouds/data

# model
h_dim: 64
e_dim: 64
z1_dim: 64
z2_dim: 64
n_layers: 3

# training
gpu: True
n_points_per_cloud: 512
bsz: 2048
lr: 1e-4
n_epochs: 10000

# evaluation
eval_frequency: 5
n_samples: 10