# data
data_dir: /pio/scratch/1/mstyp/joint-clouds/data

# model
h1_dim: 32
h2_dim: 32
e_dim: 32
ze_dim: 32
z1_dim: 2
z2_dim: 2
hid_dim: 128
n_layers: 3
activation: silu

# training
gpu: True
n_points_per_cloud: 128
bsz: 2048
lr: 1e-4
n_epochs: 3001

# evaluation
save_dir: /pio/scratch/1/mstyp/joint-clouds/results
eval_frequency: 100
n_samples: 5
n_points_per_cloud_gen: 1024