# data
data_dir: /home/sharv/Projects/joint-clouds/datasets/joint-clouds/data/MNIST2D/

# model
h_dim: 64
z_dim: 2
emb_dim: 256
encoder_hid_dim: 512
encoder_n_layers: 2
decoder_hid_dim: 512
decoder_n_layers: 3

# training
gpu: True
n_gpus: 2
n_points_per_cloud: 256
bsz: 1800
optimizer: adam
lr: 1e-5
n_epochs: 5
n_warmup_epochs: 30

# evaluation
save_dir: /home/sharv/Projects/joint-clouds/datasets/joint-clouds/results/sv
eval_frequency: 1
n_samples: 3
n_points_per_cloud_gen: 1024
